on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: |
          nix develop --impure
          echo "$DEVENV_PROFILE/bin"
          ls "$DEVENV_PROFILE/bin"
          echo "$DEVENV_PROFILE/bin" >> $GITHUB_PATH
      - run: "poetry run pytest"
  release:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.repository_owner == 'mirkolenz' && github.event_name == 'push' }}
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: |
          nix develop --impure
          echo "$DEVENV_PROFILE/bin" >> $GITHUB_PATH
      - uses: cihelper/action-semanticrelease-poetry@v1
        id: semanticrelease
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
      - name: devenv copy container
        run: |
          devenv container processes --copy \
          --copy-args="--dest-registry-token ${{ secrets.GITHUB_TOKEN }}"
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
