env:
  PYTHON_VERSION: "3.9"
  POETRY_VERSION: "1.3.1"
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cihelper/action-semanticrelease-poetry@v1
        with:
          poetry-version: "1.3.1"
          python-version: "3.9"
          pypi-token: ${{ secrets.PYPI_TOKEN }}
