env:
  PYTHON_VERSION: "3.9"
  POETRY_VERSION: "1.3.0"
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: makejinja
  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - run: "pip install poetry==${{ env.POETRY_VERSION }}"
      - run: "poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }} --no-interaction -vv"
